// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: kickoutreq.proto

package protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type KickoutReq_Reason int32

const (
	KickoutReq_ADMIN_OPT          KickoutReq_Reason = 0
	KickoutReq_OTHER_DEVICE_LOGIN KickoutReq_Reason = 1
)

// Enum value maps for KickoutReq_Reason.
var (
	KickoutReq_Reason_name = map[int32]string{
		0: "ADMIN_OPT",
		1: "OTHER_DEVICE_LOGIN",
	}
	KickoutReq_Reason_value = map[string]int32{
		"ADMIN_OPT":          0,
		"OTHER_DEVICE_LOGIN": 1,
	}
)

func (x KickoutReq_Reason) Enum() *KickoutReq_Reason {
	p := new(KickoutReq_Reason)
	*p = x
	return p
}

func (x KickoutReq_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KickoutReq_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_kickoutreq_proto_enumTypes[0].Descriptor()
}

func (KickoutReq_Reason) Type() protoreflect.EnumType {
	return &file_kickoutreq_proto_enumTypes[0]
}

func (x KickoutReq_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KickoutReq_Reason.Descriptor instead.
func (KickoutReq_Reason) EnumDescriptor() ([]byte, []int) {
	return file_kickoutreq_proto_rawDescGZIP(), []int{0, 0}
}

type KickoutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason KickoutReq_Reason `protobuf:"varint,1,opt,name=reason,proto3,enum=KickoutReq_Reason" json:"reason,omitempty"`
}

func (x *KickoutReq) Reset() {
	*x = KickoutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kickoutreq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickoutReq) ProtoMessage() {}

func (x *KickoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_kickoutreq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickoutReq.ProtoReflect.Descriptor instead.
func (*KickoutReq) Descriptor() ([]byte, []int) {
	return file_kickoutreq_proto_rawDescGZIP(), []int{0}
}

func (x *KickoutReq) GetReason() KickoutReq_Reason {
	if x != nil {
		return x.Reason
	}
	return KickoutReq_ADMIN_OPT
}

var File_kickoutreq_proto protoreflect.FileDescriptor

var file_kickoutreq_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6b, 0x69, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x72, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x69, 0x0a, 0x0a, 0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x2e, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x06,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f,
	0x4f, 0x50, 0x54, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x44,
	0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_kickoutreq_proto_rawDescOnce sync.Once
	file_kickoutreq_proto_rawDescData = file_kickoutreq_proto_rawDesc
)

func file_kickoutreq_proto_rawDescGZIP() []byte {
	file_kickoutreq_proto_rawDescOnce.Do(func() {
		file_kickoutreq_proto_rawDescData = protoimpl.X.CompressGZIP(file_kickoutreq_proto_rawDescData)
	})
	return file_kickoutreq_proto_rawDescData
}

var file_kickoutreq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kickoutreq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kickoutreq_proto_goTypes = []interface{}{
	(KickoutReq_Reason)(0), // 0: KickoutReq.Reason
	(*KickoutReq)(nil),     // 1: KickoutReq
}
var file_kickoutreq_proto_depIdxs = []int32{
	0, // 0: KickoutReq.reason:type_name -> KickoutReq.Reason
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kickoutreq_proto_init() }
func file_kickoutreq_proto_init() {
	if File_kickoutreq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kickoutreq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickoutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kickoutreq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kickoutreq_proto_goTypes,
		DependencyIndexes: file_kickoutreq_proto_depIdxs,
		EnumInfos:         file_kickoutreq_proto_enumTypes,
		MessageInfos:      file_kickoutreq_proto_msgTypes,
	}.Build()
	File_kickoutreq_proto = out.File
	file_kickoutreq_proto_rawDesc = nil
	file_kickoutreq_proto_goTypes = nil
	file_kickoutreq_proto_depIdxs = nil
}
