// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: peermsgsendreq.proto

package protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PeerMsgSendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
}

func (x *PeerMsgSendReq) Reset() {
	*x = PeerMsgSendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peermsgsendreq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerMsgSendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMsgSendReq) ProtoMessage() {}

func (x *PeerMsgSendReq) ProtoReflect() protoreflect.Message {
	mi := &file_peermsgsendreq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMsgSendReq.ProtoReflect.Descriptor instead.
func (*PeerMsgSendReq) Descriptor() ([]byte, []int) {
	return file_peermsgsendreq_proto_rawDescGZIP(), []int{0}
}

func (x *PeerMsgSendReq) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *PeerMsgSendReq) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

var File_peermsgsendreq_proto protoreflect.FileDescriptor

var file_peermsgsendreq_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x65, 0x65, 0x72, 0x6d, 0x73, 0x67, 0x73, 0x65, 0x6e, 0x64, 0x72, 0x65, 0x71,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x0e, 0x50, 0x65, 0x65, 0x72, 0x4d, 0x73,
	0x67, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_peermsgsendreq_proto_rawDescOnce sync.Once
	file_peermsgsendreq_proto_rawDescData = file_peermsgsendreq_proto_rawDesc
)

func file_peermsgsendreq_proto_rawDescGZIP() []byte {
	file_peermsgsendreq_proto_rawDescOnce.Do(func() {
		file_peermsgsendreq_proto_rawDescData = protoimpl.X.CompressGZIP(file_peermsgsendreq_proto_rawDescData)
	})
	return file_peermsgsendreq_proto_rawDescData
}

var file_peermsgsendreq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_peermsgsendreq_proto_goTypes = []interface{}{
	(*PeerMsgSendReq)(nil), // 0: PeerMsgSendReq
}
var file_peermsgsendreq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_peermsgsendreq_proto_init() }
func file_peermsgsendreq_proto_init() {
	if File_peermsgsendreq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_peermsgsendreq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerMsgSendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_peermsgsendreq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peermsgsendreq_proto_goTypes,
		DependencyIndexes: file_peermsgsendreq_proto_depIdxs,
		MessageInfos:      file_peermsgsendreq_proto_msgTypes,
	}.Build()
	File_peermsgsendreq_proto = out.File
	file_peermsgsendreq_proto_rawDesc = nil
	file_peermsgsendreq_proto_goTypes = nil
	file_peermsgsendreq_proto_depIdxs = nil
}
